# Site settings
title: Sreeharsha Bandi
description: 'Some random stuff related to my research work goes here!'
url: 'http://sreeharshabandi.github.io'
baseurl: '/jekyll-uno'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Sreeharsha Bandi'
  email: sreeharsha.bandi@outlook.com
  twitter_username: 0xharsha
  facebook_username: 
  github_username:  0xharsha
  linkedin_username:  bandi-sreeharsha

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
